// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM2s1YZT8GkF8fVlC8oF0cjjV0P5Nn5zM',
    appId: '1:211121558373:web:0442326ceda6cc4c20078c',
    messagingSenderId: '211121558373',
    projectId: 'music-app-c832e',
    authDomain: 'music-app-c832e.firebaseapp.com',
    storageBucket: 'music-app-c832e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAcE1t2gfAedjQyNfO7Qkitx7_QFTrR8k',
    appId: '1:211121558373:android:ee5e81f399b3107920078c',
    messagingSenderId: '211121558373',
    projectId: 'music-app-c832e',
    storageBucket: 'music-app-c832e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT8ZnZMjfmB6vudiNxiKF6SaSn-11_PrE',
    appId: '1:211121558373:ios:75edd2aa2616c4b320078c',
    messagingSenderId: '211121558373',
    projectId: 'music-app-c832e',
    storageBucket: 'music-app-c832e.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT8ZnZMjfmB6vudiNxiKF6SaSn-11_PrE',
    appId: '1:211121558373:ios:75edd2aa2616c4b320078c',
    messagingSenderId: '211121558373',
    projectId: 'music-app-c832e',
    storageBucket: 'music-app-c832e.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM2s1YZT8GkF8fVlC8oF0cjjV0P5Nn5zM',
    appId: '1:211121558373:web:b5d930b39228794b20078c',
    messagingSenderId: '211121558373',
    projectId: 'music-app-c832e',
    authDomain: 'music-app-c832e.firebaseapp.com',
    storageBucket: 'music-app-c832e.firebasestorage.app',
  );
}
